### ISSUE TITLE
REI - Plus button not available crafting terminal

### ISSUE THREAD

**Issue by Vixeliz** [tom5454/Toms-Storage#111]
The issue:
![20220615_17h53m08s_grim](https://user-images.githubusercontent.com/38061852/173955399-c45b746d-6bfd-4529-ac4a-672d599f908c.png)
To show it is crafting terminal:
![20220615_17h53m55s_grim](https://user-images.githubusercontent.com/38061852/173955523-4a6af7e9-1b08-4d97-aaac-eed73bd4e3d7.png)

I'm on the latest version for 1.19 let me know if you need any other info

**Comment by tom5454** [comment]
Fixed in 1.3.4

**Comment by whtft** [comment]
Still not working on forge

**Versions**:
- Base game: **1.19**
- Forge: **41.0.38**
- Tom's Storage: **1.3.5**
- REI: **9.0.491**

Works fine with JEI **11.0.0.206** though so that's a silver lining.

**Comment by tom5454** [comment]
REI on forge uses JEI's api, Report this to REI.
